name: 'Makerminds, Inc.'
favicon: null
layout_spectrum: 0.6982602085918188
typography_spectrum: 0.431896616704762
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.025022929534316063
  lightness: 0.11272770166397095
  saturation: 0.678777894936502
  rhythmicContrast: 0.2316880878061056
purpose: []
