name: 'Makerminds, Inc.'
favicon: null
layout_spectrum: 0.5180463751312345
typography_spectrum: 0.23121863836422563
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.1622803418431431
  lightness: 0.3561495183967054
  saturation: 0.7939613081980497
  rhythmicContrast: 0.14081924757920206
purpose: []
