name: 'Makerminds, Inc.'
favicon: null
layout_spectrum: 0.07650362583808601
typography_spectrum: 0.8076840175781399
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.7254845784045756
  lightness: 0.9052636553533375
  saturation: 0.9849702892825007
  rhythmicContrast: 0.6109055283013731
purpose: []
