name: 'Makerminds, Inc.'
favicon: null
layout_spectrum: 0.5199162573553622
typography_spectrum: 0.5285826863255352
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8820424810983241
  lightness: 0.5601656995713711
  saturation: 0.14838146255351603
  rhythmicContrast: 0.4393381350673735
purpose: []
